import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { HeaderMenu } from "@/components/header/header-menu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "OOKS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
            {/* <header className="flex justify-center top-0 left-0 right-0 z-50 border-2 border-solid border-red-700"> */}
      {/* </header> */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <HeaderMenu />
        {children}
      </body>
    </html>
  );
}
